server:
  port: ${PORT:8080}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7080/realms/fiap
          jwk-set-uri: http://localhost:7080/realms/fiap/protocol/openid-connect/certs

  datasource:
    url: jdbc:postgresql://localhost:5432/veiculos
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true